spring: 
    profiles: 
        active: 
        - dev

---
spring: 
    profiles: dev
    application: 
        name: config-dev
server:
  port: 7200   

---
spring: 
    profiles: test
    application: 
        name: config-test
