spring: 
    profiles: 
        active: 
        - dev

---
server:
  port: 8091
spring:
  profiles: dev
  application:
    name: USERPROVIDER
  datasource:
    url: jdbc:mysql://10.222.48.19:3306/todolist?characterEncoding=utf8&useSSL=false
    username: carlos
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9966/eureka/
---
server:
  port: 8091
spring:
  profiles: dev
  application:
    name: USERPROVIDER
  datasource:
    url: jdbc:mysql://10.222.48.19:3306/todolist?characterEncoding=utf8&useSSL=false
    username: carlos
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9966/eureka/